events { }

http {
    server {
        listen 80;
        server_name localhost;

        # Proxy everything to the app
        location / {
            proxy_pass http://app:5000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            include /etc/nginx/conf.d/cors.conf
        }
          # === Google  ===
        location /proxy/google/ {
            rewrite ^/proxy/google/(.*)$ /$1 break;
            proxy_ssl_server_name on;
            proxy_pass https://google.com;
            include /etc/nginx/conf.d/cors.conf;
        }
        # === FakeStore API ===
        location /proxy/fakestore/ {
            rewrite ^/proxy/fakestore/(.*)$ /$1 break;
            proxy_ssl_server_name on;
            proxy_pass https://fakestoreapi.com;
            include /etc/nginx/conf.d/cors.conf;
        }

        # === Dog CEO API ===
        location /proxy/dog/ {
            rewrite ^/proxy/dog/(.*)$ /$1 break;
            proxy_ssl_server_name on;
            proxy_pass https://dog.ceo/api/;
            include /etc/nginx/conf.d/cors.conf;
        }

        # === JSONPlaceholder API ===
        location /json/ {
            # rewrite ^/proxy/json/(.*)$ /$1 break;
            proxy_ssl_server_name on;
            proxy_pass https://jsonplaceholder.typicode.com/;
            include /etc/nginx/conf.d/cors.conf;
        }
    }
}

